name: Azure Static Web Apps CI/CD with OIDC

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write          # Needed to get OIDC token from GitHub
      contents: read           # For checkout

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: plant-tracker-frontend
        run: npm install

      - name: Build Angular app
        working-directory: plant-tracker-frontend
        run: npm run build

      - name: Deploy to Azure Static Web Apps using OIDC
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: plant-tracker-frontend
          output_location: dist/plant-tracker-frontend/browser
          api_location: ""
          github_id_token: ${{ steps.get_oidc_token.outputs.token }}

      - name: Get OIDC token
        id: get_oidc_token
        uses: actions/github-script@v6
        with:
          script: |
            return await github.actions.getIDToken()
          result-encoding: string
