name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # For OIDC token if needed
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: plant-tracker-frontend
        run: npm install

      - name: Build Angular app
        working-directory: plant-tracker-frontend
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_HILL_0573B641E }}
          action: upload
          app_location: plant-tracker-frontend
          output_location: dist/plant-tracker-frontend/browser
          api_location: ""
