name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        if: github.event.action != 'closed'
        working-directory: plant-tracker-frontend
        run: npm install

      - name: Build Angular app
        if: github.event.action != 'closed'
        working-directory: plant-tracker-frontend
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_HILL_0573B641E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "plant-tracker-frontend"
          output_location: "dist/plant-tracker-frontend"
